In [19]:
import pandas as pd
import pickle
import numpy as np
model=pickle.load(open("/Users/vn55le3/Downloads/DS2023Talendig/7-LogisticRegression/modelo_logistico.sav",'rb'))
X=[]
for i in range(4):
    cad="Digite la caracteristica"+str(i+1)
    d=float(input(cad))
    print(d)
    X.append(d)
X=np.array(X)
pred=model.predict(X.reshape(1,-1))

1.1
1.2
1.3
1.4


In [20]:
pred

array([1])

In [16]:

X

array([1., 1., 1., 1.])

In [17]:
X.reshape(1,-1)

array([[1., 1., 1., 1.]])